# POST http://localhost:3000/api/v1/register
# Content-Type: application/json

# {
#     "nomor_pelanggan": "0812311231",
#     "nama": "John Doe",
#     "alamat": "123 Main St, Anytown, USA",
#     "email": "email5@example.com",
#     "password": "securepassword",
#     "confirm_password": "securepassword"
# }

# POST http://localhost:3000/api/v1/login
# Content-Type: application/json

# {
#     "email": "email2@example.com",
#     "password": "securepassword"
# }

# POST http://localhost:3000/api/v1/logout
# Content-Type: application/json

# POST http://localhost:3000/api/v1/forget-password
# Content-Type: application/json

# {
#     "email": "email1@example.com"  
# }

# POST http://localhost:3000/api/v1/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsMUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MzAyNDA0MiwiZXhwIjoxNzYzNjI4ODQyfQ.bv73uScPhWAb7ijH-jDZId_AR2nnm-oNuLQHrlBYuso
# Content-Type: application/json

# {
#     "newPassword": "newsecurepassword4"
# }

# GET http://localhost:3000/api/v1/users?page=3&limit=10
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyYzA4YWUyLWRiMTgtNGU3Ny05ZDI2LWM1ZmE0NGYxMWNmZCIsImVtYWlsIjoiZW1haWwyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYyOTY1NjcwLCJleHAiOjE3NjM1NzA0NzB9.28GUZEkIl4YbkLNCZ1zlEiogGmOQ56G4j44u-MbXq_0
# Content-Type: application/json

# POST https://9b4a848e5089.ngrok-free.app/api/v1/payment
# Content-Type: application/json

# {
#     "amount": 150000,
#     "product": "Paket B",
#     "email": "chan.halim98@gmail.com",
#     "customerName": "chandra",
#     "handphone": "0895342754470",
#     "id_users": "a01c6a7e-db02-464f-be5a-966a8978e623"
# }

# POST https://9b4a848e5089.ngrok-free.app/api/v1/payment/callback
# Content-Type: application/json

# {
#   "merchantOrderId": "SAN-1764090793652-59473",
#   "resultCode": "00"
# }
