# POST http://localhost:3000/api/register
# Content-Type: application/json

# {
#     "nomor_pelanggan": "1234567890",
#     "nama": "John Doe",
#     "alamat": "123 Main St, Anytown, USA",
#     "email": "email2@example.com",
#     "password": "securepassword"
# }

# POST http://localhost:3000/api/login
# Content-Type: application/json

# {
#     "email": "email1@example.com",
#     "password": "securepassword"
# }

# POST http://localhost:3000/api/logout
# Content-Type: application/json

# POST http://localhost:3000/api/forget-password
# Content-Type: application/json

# {
#     "email": "email1@example.com"  
# }

# POST http://localhost:3000/api/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsMUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MzAyNDA0MiwiZXhwIjoxNzYzNjI4ODQyfQ.bv73uScPhWAb7ijH-jDZId_AR2nnm-oNuLQHrlBYuso
# Content-Type: application/json

# {
#     "newPassword": "newsecurepassword4"
# }

# GET http://localhost:3000/api/users?page=3&limit=10
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyYzA4YWUyLWRiMTgtNGU3Ny05ZDI2LWM1ZmE0NGYxMWNmZCIsImVtYWlsIjoiZW1haWwyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYyOTY1NjcwLCJleHAiOjE3NjM1NzA0NzB9.28GUZEkIl4YbkLNCZ1zlEiogGmOQ56G4j44u-MbXq_0
# Content-Type: application/json

POST http://localhost:3000/api/payment
Content-Type: application/json

{
    "amount": 150000,
    "product": "Paket B",
    "customerEmail": "chan.halim98@gmail.com",
    "customerName": "chandra",
    "phoneNumber": "081231712311"
}